/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ArmRegistryProperties class.
 * @constructor
 * @member {string} [registryName]
 * 
 * @member {string} [loginServer]
 * 
 * @member {string} [username]
 * 
 * @member {string} [key]
 * 
 * @member {date} [date]
 * 
 */
function ArmRegistryProperties() {
}

/**
 * Defines the metadata of ArmRegistryProperties
 *
 * @returns {object} metadata of ArmRegistryProperties
 *
 */
ArmRegistryProperties.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'ArmRegistryProperties',
    type: {
      name: 'Composite',
      className: 'ArmRegistryProperties',
      modelProperties: {
        registryName: {
          required: false,
          serializedName: 'registryName',
          type: {
            name: 'String'
          }
        },
        loginServer: {
          required: false,
          serializedName: 'loginServer',
          type: {
            name: 'String'
          }
        },
        username: {
          required: false,
          serializedName: 'username',
          type: {
            name: 'String'
          }
        },
        key: {
          required: false,
          serializedName: 'key',
          type: {
            name: 'String'
          }
        },
        date: {
          required: false,
          serializedName: 'date',
          type: {
            name: 'DateTime'
          }
        }
      }
    }
  };
};

module.exports = ArmRegistryProperties;
