/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

/**
 * @class
 * Initializes a new instance of the Registry class.
 * @constructor
 * @member {string} [id]
 * 
 * @member {string} [name]
 * 
 * @member {string} [location]
 * 
 * @member {object} [tags]
 * 
 * @member {string} [type]
 * 
 * @member {object} [properties]
 * 
 * @member {string} [properties.loginServer]
 * 
 * @member {string} [properties.username]
 * 
 * @member {string} [properties.key]
 * 
 * @member {date} [properties.creationDate]
 * 
 */
function Registry() {
}

/**
 * Defines the metadata of Registry
 *
 * @returns {object} metadata of Registry
 *
 */
Registry.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Registry',
    type: {
      name: 'Composite',
      className: 'Registry',
      modelProperties: {
        id: {
          required: false,
          serializedName: 'id',
          type: {
            name: 'String'
          }
        },
        name: {
          required: false,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        },
        location: {
          required: false,
          serializedName: 'location',
          type: {
            name: 'String'
          }
        },
        tags: {
          required: false,
          serializedName: 'tags',
          type: {
            name: 'Dictionary',
            value: {
                required: false,
                serializedName: 'StringElementType',
                type: {
                  name: 'String'
                }
            }
          }
        },
        type: {
          required: false,
          readOnly: true,
          serializedName: 'type',
          type: {
            name: 'String'
          }
        },
        properties: {
          required: false,
          serializedName: 'properties',
          type: {
            name: 'Composite',
            className: 'RegistryProperties'
          }
        }
      }
    }
  };
};

module.exports = Registry;
