/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the RegistryProperties class.
 * @constructor
 * @member {string} [loginServer]
 * 
 * @member {string} [username]
 * 
 * @member {string} [key]
 * 
 * @member {date} [creationDate]
 * 
 */
function RegistryProperties() {
}

/**
 * Defines the metadata of RegistryProperties
 *
 * @returns {object} metadata of RegistryProperties
 *
 */
RegistryProperties.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'RegistryProperties',
    type: {
      name: 'Composite',
      className: 'RegistryProperties',
      modelProperties: {
        loginServer: {
          required: false,
          serializedName: 'loginServer',
          type: {
            name: 'String'
          }
        },
        username: {
          required: false,
          serializedName: 'username',
          type: {
            name: 'String'
          }
        },
        key: {
          required: false,
          serializedName: 'key',
          type: {
            name: 'String'
          }
        },
        creationDate: {
          required: false,
          serializedName: 'creationDate',
          type: {
            name: 'DateTime'
          }
        }
      }
    }
  };
};

module.exports = RegistryProperties;
