/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 * 
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

var util = require('util');

/**
 * @class
 * Initializes a new instance of the ResourceListRegistryParameters class.
 * @constructor
 * @member {array} [value]
 * 
 */
function ResourceListRegistryParameters() {
}

/**
 * Defines the metadata of ResourceListRegistryParameters
 *
 * @returns {object} metadata of ResourceListRegistryParameters
 *
 */
ResourceListRegistryParameters.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'ResourceList[RegistryParameters]',
    type: {
      name: 'Composite',
      className: 'ResourceListRegistryParameters',
      modelProperties: {
        value: {
          required: false,
          serializedName: 'value',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'RegistryParametersElementType',
                type: {
                  name: 'Composite',
                  className: 'RegistryParameters'
                }
            }
          }
        }
      }
    }
  };
};

module.exports = ResourceListRegistryParameters;
